apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: bookstore-microservices
  labels:
    app: account
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
  - port: 80
    targetPort: http-server
