apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: bookstore-microservices
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: http-server
    nodePort: 30080
