apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: bookstore-microservices
  labels:
    app: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - port: 80
    targetPort: http-server
