apiVersion: v1
kind: Service
metadata:
  name: security
  namespace: bookstore-microservices
  labels:
    app: security
spec:
  type: ClusterIP
  selector:
    app: security
  ports:
  - port: 80
    targetPort: http-server
